{
 "title": "Aiven Monitoring & Observability",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Account related", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Teams per Account",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (account)(aiven_account_team_count_total)",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Number of Members per Team for an Account",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (account, team)(aiven_account_team_member_count_total)",
     "legendFormat": "{{project}}"
    }
   ]
  },
  { "title": "Project related", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Projects",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(aiven_project_count_total)" }
   ]
  },
  {
   "title": "Number of Services per Project",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (project)(aiven_service_count_total)",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "VPCs per Project",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (project)(aiven_project_vpc_count_total)",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "VPC Peerings per Project",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by (project)(aiven_project_vpc_peering_count_total)",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Estimated Billing per Project",
   "type": "table",
   "description": "Note: The estimated billing is misleading, basically it is a \"costs-until-now\" overview.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (project)(aiven_project_estimated_billing_total/ day_of_month() * days_in_month())",
     "legendFormat": "{{project}}"
    }
   ]
  },
  { "title": "Service related", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Number of Service Users per Service",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by (project, service)(aiven_service_serviceuser_count_total)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Number of Nodes per Service",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum by (project, service)(aiven_service_node_count_total)",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Booked Plan per Service",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum by (project, plan, A_Service)(label_replace(aiven_service_booked_plan_info, \"A_Service\", \"$1\", \"service\", \"(.*)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Service Users per Service",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "sum by (project, service)(aiven_service_serviceuser_count_total)",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Unhealthy Nodes per Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum(aiven_service_node_state_info{state!=\"running\"}) by (service, node_name, state) or 0",
     "legendFormat": "{{service}} {{node_name}} - {{state}}"
    }
   ]
  },
  {
   "title": "Number of Topics per Kafka Service",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "sum by (project, service)(aiven_service_topic_count_total)",
     "legendFormat": "{{project}}"
    }
   ]
  }
 ]
}